ALTER TABLE EIGENTEIL ADD (
  KONSTRUKTEUR VARCHAR(100),
  KONSTRUKTIONSDATUM TIMESTAMP
);
ALTER TABLE TEIL MODIFY TEIL_ART CHAR(1) not null;
ALTER TABLE TEIL ADD CONSTRAINT BEZEICHNUNG_UNIQUE UNIQUE(BEZEICHNUNG);
ALTER TABLE TEIL ADD CONSTRAINT TEIL_ART_ENUM CHECK(TEIL_ART IN ('A', 'E', 'F'));
ALTER TABLE TEIL MODIFY LAGERBESTAND default 0;

commit;



