-- Bestellpolitik soll ebenfalss als enumeration abgebildet werden, da diese
-- fix vorgegeben sind
CREATE TABLE BESTELLPOLITIK (
  BESTELL_ART VARCHAR(20),
  CONSTRAINT BESTELLPOLITIK_PK PRIMARY KEY(BESTELL_ART)
);

CREATE TABLE TEIL (
  TNR INTEGER not null,
  BEZEICHNUNG VARCHAR(255) not null,
  TEIL_ART VARCHAR(10),
  LAGERBESTAND INTEGER not null,
  MENGENEINHEIT VARCHAR(10) not null,
  CONSTRAINT TEIL_PK PRIMARY KEY(TNR)
);

CREATE TABLE ARTIKEL (
  TNR_ID INTEGER not null,
  VERKAUFSPREIS NUMBER(9, 2) not null,
  CONSTRAINT ARTIKEL_PK PRIMARY KEY(TNR_ID),
  CONSTRAINT ARTIKEL_TNR_ID_FK FOREIGN KEY(TNR_ID) REFERENCES TEIL(TNR)
);

CREATE TABLE FREMDTEIL (
  TNR_ID INTEGER not null,
  BESTELL_ART_ID VARCHAR(20) not null,
  CONSTRAINT FREMDTEIL_PK PRIMARY KEY(TNR_ID),
  CONSTRAINT FREMDTEIL_BESTELL_ART_ID_FK FOREIGN KEY(BESTELL_ART_ID) REFERENCES BESTELLPOLITIK(BESTELL_ART)
);

CREATE TABLE EIGENTEIL (
  TNR_ID INTEGER not null,
  LOSGROESSE INTEGER not null,
  CONSTRAINT EIGENTEIL_PK PRIMARY KEY(TNR_ID),
  CONSTRAINT EIGENTEIL_TNR_ID_FK FOREIGN KEY(TNR_ID) REFERENCES TEIL(TNR)
);

CREATE TABLE STRUKTUR (
  OBER_TNR_ID INTEGER not null,
  UNTER_TNR_ID INTEGER not null,
  MENGE INTEGER not null,
  CONSTRAINT STRUKTUR_ID PRIMARY KEY(OBER_TNR_ID, UNTER_TNR_ID),
  CONSTRAINT STRUKTUR_OBER_TNR_ID FOREIGN KEY(OBER_TNR_ID) REFERENCES TEIL(TNR),
  CONSTRAINT STRUKTUR_UNTER_TNR_ID FOREIGN KEY(UNTER_TNR_ID) REFERENCES TEIL(TNR)
);

CREATE TABLE ARBEITSPLAN (
  APNR INTEGER not null,
  ERSTELLER VARCHAR(100) not null,
  ERSTELLUNGS_DATUM TIMESTAMP not null,
  TNR_ID INTEGER not null,
  CONSTRAINT ARBEITSPLAN_PK PRIMARY KEY(APNR),
  CONSTRAINT ARBEITSPLAN_TNR_ID_FK FOREIGN KEY(TNR_ID) REFERENCES TEIL(TNR)
);

CREATE TABLE TECHNISCHES_VERFAHREN (
  VNR INTEGER not null,
  BEZEICHNUNG VARCHAR(255),
  CONSTRAINT TECH_VERF_VNR_ID_PK PRIMARY KEY(VNR)
);

CREATE TABLE ARBEITSGANG (
  APNR_ID INTEGER not null,
  AGNR INTEGER not null,
  VNR_ID INTEGER not null,
  CONSTRAINT ARBEITSGANG_PK PRIMARY KEY(APNR_ID, AGNR),
  CONSTRAINT ARBEITSPLAN_APNR_ID_FK FOREIGN KEY(APNR_ID) REFERENCES ARBEITSPLAN(APNR),
  CONSTRAINT TECHN_VERF_VNR_ID_FK FOREIGN KEY(VNR_ID) REFERENCES TECHNISCHES_VERFAHREN(VNR)
);

CREATE TABLE BETRIEBSMITTEL (
  BMNR INTEGER not null,
  BEZEICHNUNG VARCHAR(255),
  WARTUNG TIMESTAMP not null,
  CONSTRAINT BETRIEBSMITTEL_FK PRIMARY KEY(BMNR)
);

-- Da es keinen reinen TIME Datentyp gibt, also der nur Zeit im Format Bsp.: hh:mm:ss
-- speichert wird die Zeit mittels INTEGER (Sekunden) gespeichert und muss daher
-- auch applikatorisch in ein Datumsformat umgewandelt werden.
CREATE TABLE AG_BM_ZUORDNUNG (
  APNR_ID INTEGER not null,
  AGNR_ID INTEGER not null,
  BMNR_ID INTEGER not null,
  RUESTZEIT INTEGER not null,
  ARBEITSZEIT INTEGER not null,
  CONSTRAINT AG_BM_ZUORDNUNG_PK PRIMARY KEY(APNR_ID, AGNR_ID, BMNR_ID),
  CONSTRAINT AG_BM_ZUOR_ARB_FK FOREIGN KEY(APNR_ID, AGNR_ID) REFERENCES ARBEITSGANG(APNR_ID, AGNR)
);

CREATE TABLE AG_KOMP_ZUORDNUNG (
  APNR_ID INTEGER not null,
  AGNR_ID INTEGER not null,
  TNR_ID INTEGER not null,
  MENGE INTEGER not null,
  CONSTRAINT AG_KOMP_ZUORDNUNG_PK PRIMARY KEY(APNR_ID, AGNR_ID, TNR_ID),
  CONSTRAINT AG_KOMP_ZUOR_APNR_ID_FK FOREIGN KEY(APNR_ID, AGNR_ID) REFERENCES ARBEITSGANG (APNR_ID, AGNR),
  CONSTRAINT AG_KOMP_ZUOR_TNR_ID_FK FOREIGN KEY(TNR_ID) REFERENCES TEIL(TNR)
);

commit;

