DROP TABLE AG_KOMP_ZUORDNUNG;
DROP TABLE AG_BM_ZUORDNUNG;
DROP TABLE BETRIEBSMITTEL;
DROP TABLE ARBEITSGANG;
DROP TABLE TECHNISCHES_VERFAHREN;
DROP TABLE ARBEITSPLAN;
DROP TABLE STRUKTUR;
DROP TABLE EIGENTEIL;
DROP TABLE FREMDTEIL;
DROP TABLE ARTIKEL;
DROP TABLE TEIL;
DROP TABLE BESTELLPOLITIK;

commit;