CREATE TABLE AUDIT_TABLE_EMP(
  ID NUMBER NOT NULL,
  MOD_USR VARCHAR(100) NOT NULL,
  MOD_DAT TIMESTAMP NOT NULL,
  ACCESS_TYPE VARCHAR(10) NOT NULL,
  EMPNO NUMBER NOT NULL,
  CONSTRAINT PK_ID PRIMARY KEY(ID),
  CONSTRAINT ACCESS_TYPE_ENUM CHECK(ACCESS_TYPE IN ('INSERT', 'UPDATE', 'DELETE')),
  CONSTRAINT FK_EMP_EMP_NR FOREIGN KEY(EMPNO) REFERENCES EMP(EMPNO)
);

CREATE TABLE AUDIT_TABLE_EMP_VALUES(
  ATE_ID NUMBER NOT NULL,
  POSITION NUMBER NOT NULL,
  ATTRIBUTE_NAME VARCHAR(10) NOT NULL,
  ATTRIBUTE_OLD NUMBER NOT NULL,
  ATTRIBUTE_NEW NUMBER NOT NULL,
  CONSTRAINT PK_ATE_ID PRIMARY KEY(ATE_ID, POSITION),
  CONSTRAINT FK_ATE_ID FOREIGN KEY(ATE_ID) REFERENCES AUDIT_TABLE_EMP(ID)
);

CREATE SEQUENCE SEQ_AUTID_TABLE_EMPT;

-- Drop statements for testing 
-- DROP TABLE AUDIT_TABLE_EMP_VALUES;
-- DROP TABLE AUDIT_TABLE_EMP;
-- DROP SEQUENCE SEQ_AUTID_TABLE_EMPT;
